project_0:
  url: "/"
  description: "Environment Set Up"
project_1:
  url: "/"
  description: "Custom Home Page Route"
project_2:
  url: "/pages/project_2"
  description: "Description of Bootstrap set up"
project_3 and 4:
  url: "/calendar"
  description: "A basic interactive calendar (persistent)"